baseurl: ''
permalink: pretty
markdown: rdiscount
prose:
  rooturl: '_posts'
  siteurl: 'http://galya.podari-zhizn.ru/'
  media: 'media'
  metadata:
    _posts/articles:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "lead"
        field:
          element: "textarea"
          label: "Article abstract"
          value: ""
      - name: "category"
        field:
          element: "hidden"
          value: "article"
      - name: "layout"
        field:
          element: "hidden"
          value: "article"
      - name: "author"
        field:
          element: "text"
          label: "Author"
          value: ""
      - name: "source"
        field:
          element: "text"
          label: "Source link"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""